[package]

name = "tower-service"
version = "0.1.0"
license = "MIT"
authors = ["Carl Lerche <me@carllerche.com>"]
description = """
The core `Service` trait for Tower.
"""
documentation = "https://docs.rs/tower-service"
homepage = "https://github.com/tower-rs/tower"
repository = "https://github.com/tower-rs/tower"
readme = "README.md"
publish = false

[dependencies]
futures = "0.1"
